spring:
  application:
    name: job-app
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  info:
    env:
      enabled: true
info:
  app:
    name: Spring boot
    description: hello
    version: 1.1.1
