spring:
  application:
    name: job-app
  datasource:
    url: jdbc:postgresql://localhost:5432/job_app
    username: ${PSQL_USERNAME}
    password: ${PSQL_PASSWORD}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  info:
    env:
      enabled: true
info:
  app:
    name: Spring boot
    description: hello
    version: 1.1.1
